export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
export const REGISTRAR_REQUEST = "REGISTRAR_REQUEST";
export const REGISTRAR_REQUEST_SUCCESS = "REGISTRAR_REQUEST_SUCCESS";
export const REGISTRAR_REQUEST_ERROR = "REGISTRAR_REQUEST_ERROR";
